### PR TITLE
update version of package-manifest spec

### PR DESCRIPTION
**Pull request by mhhf**
I remember the request that this should be a string rather a integer.

### CODE REVIEW

**Comment by pipermerriam** [comment]
Why version 2?

**Comment by mhhf** [comment]
i changed it, so i had to update the version.

**Comment by tcoulter** [comment]
Are we at a decided upon version 1 yet?

**Comment by pipermerriam** [comment]
I don't think we're at that point yet.  Can we agree that we'll all continue to update our tools until we have a releasable product and that will be called version `"1"`

**Comment by pipermerriam** [comment]
Releasable product is probably defined as at least two of our frameworks being able to run

`thing install ipfs://Qm....` 

where the IPFS link there points at a Release Manifest and all dependencies are also direct links to Release Manifest files (i.e. we are not requiring any registrar related features).

**Pull request merged**
