### PR TITLE
Disallow uppercase characters in package names

### PR DESCRIPTION
**Pull request by pipermerriam**
Don't allow uppercase characters in package names.

### CODE REVIEW

**Comment by tcoulter** [comment]
👍

**Comment by VoR0220** [comment]
No

**Comment by pipermerriam** [comment]
@VoR0220 I merged this due to the 3:1 vote.  I am still curious to hear your *why* but without knowing the *why* I chose to go ahead and move forward with this.  Still of course open for discussion.

**Comment by VoR0220** [comment]
because if we want a mixed case, that could be useful. Also enables more differentiation.

**Comment by tcoulter** [comment]
I don't think we should allow people to make a distinction between `monax-stdlib`, `Monax-stdlib`, and `monax-STDlib`. Actually, thinking about it we probably don't want underscores unless we want to allow people to create `monax-stdlib` and `monax_stdlib`. We have enough naming issues already.

I vote no uppercase, no underscore.

**Comment by VoR0220** [comment]
so I agree with not wanting to make the distinction, but I think mixedCase is useful.

**Comment by tcoulter** [comment]
Right, but how is it useful given my examples above of how it's not useful?

**Comment by tcoulter** [comment]
Reducing the namespace (character space) is probably better for everyone. e.g., http://bgr.com/2016/11/21/fake-google-vitaly-popov-scam-spam/

**Comment by tcoulter** [comment]
As an aside, is this something we can actually enforce?

**Comment by VoR0220** [comment]
I suppose from the package manager level. But its kind of like an agreement we all make to do this. Not really enforceable for all newcomers who think our package managers suck :p

**Pull request merged**
